# site settings

title: Hedwy.Art
description: nothing special, just Hedwy
taglong: nothing special, just Hedwy
tagshort: nothing special, just Hedwy
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/username/itshedwy.github.io

# author settings

author:
  name: Hedwy
  email: itshedwy@gmail.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: false
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
